/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["AuthController_refresh_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["AuthController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate refresh token */
        post: operations["AuthController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users (admin) */
        get: operations["UsersAdminController_findAll_v1"];
        put?: never;
        /** Create user */
        post: operations["UsersAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by id (admin) */
        get: operations["UsersAdminController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete user */
        delete: operations["UsersAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Update user */
        patch: operations["UsersAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories */
        get: operations["CategoriesController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category by slug */
        get: operations["CategoriesController_findOne_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories (admin) */
        get: operations["CategoriesAdminController_findAll_v1"];
        put?: never;
        /** Create category */
        post: operations["CategoriesAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category by id (admin) */
        get: operations["CategoriesAdminController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete category */
        delete: operations["CategoriesAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Update category */
        patch: operations["CategoriesAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all products */
        get: operations["ProductsController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by slug */
        get: operations["ProductsController_findOne_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all products (admin) */
        get: operations["ProductsAdminController_findAll_v1"];
        put?: never;
        /** Create product */
        post: operations["ProductsAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by id (admin) */
        get: operations["ProductsAdminController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete product */
        delete: operations["ProductsAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Update product */
        patch: operations["ProductsAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/admin/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create product variant */
        post: operations["ProductsAdminController_createVariant_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{id}/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete product variant */
        delete: operations["ProductsAdminController_removeVariant_v1"];
        options?: never;
        head?: never;
        /** Update product variant */
        patch: operations["ProductsAdminController_updateVariant_v1"];
        trace?: never;
    };
    "/api/v1/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file to temporary storage */
        post: operations["FilesController_upload_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create order */
        post: operations["OrdersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order by id */
        get: operations["OrdersController_findOne_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all orders (admin) */
        get: operations["OrdersAdminController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order by id (admin) */
        get: operations["OrdersAdminController_findOne_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update order status */
        patch: operations["OrdersAdminController_updateStatus_v1"];
        trace?: never;
    };
    "/api/v1/reviews/product/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get approved reviews for a product */
        get: operations["ReviewsController_findByProduct_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a review */
        post: operations["ReviewsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all reviews (admin) */
        get: operations["ReviewsAdminController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get review by id (admin) */
        get: operations["ReviewsAdminController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete review */
        delete: operations["ReviewsAdminController_remove_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update review status */
        patch: operations["ReviewsAdminController_updateStatus_v1"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponseDto: {
            user: {
                id: number;
                email: string;
                first_name: string;
                last_name: string;
                /** @enum {string} */
                role: "admin" | "user";
                /** Format: date-time */
                created_at: string;
            };
            access_token: string;
            refresh_token: string;
            access_expires_at: string;
        };
        ApiResponseOfLoginResponseDto: {
            data: components["schemas"]["LoginResponseDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        RefreshDto: {
            refresh_token: string;
        };
        RefreshResponseDto: {
            access_token: string;
            access_expires_at: string;
        };
        ApiResponseOfRefreshResponseDto: {
            data: components["schemas"]["RefreshResponseDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        AuthUserDto: {
            id: number;
            email: string;
            first_name: string;
            last_name: string;
            /** @enum {string} */
            role: "admin" | "user";
            /** Format: date-time */
            created_at: string;
        };
        ApiResponseOfAuthUserDto: {
            data: components["schemas"]["AuthUserDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        LogoutDto: {
            refresh_token: string;
        };
        UserDto: {
            id: number;
            email: string;
            first_name: string;
            last_name: string;
            /** @enum {string} */
            role: "admin" | "user";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiArrayResponseOfUserDto: {
            data: components["schemas"]["UserDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        ApiResponseOfUserDto: {
            data: components["schemas"]["UserDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateUserDto: {
            /** Format: email */
            email: string;
            password: string;
            first_name: string;
            last_name: string;
            /**
             * @default user
             * @enum {string}
             */
            role: "admin" | "user";
        };
        UpdateUserDto: {
            /** Format: email */
            email?: string;
            password?: string;
            first_name?: string;
            last_name?: string;
            /**
             * @default user
             * @enum {string}
             */
            role: "admin" | "user";
        };
        CategoryDto: {
            id: number;
            name: string;
            slug: string;
            description: string | null;
            sort_order: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiArrayResponseOfCategoryDto: {
            data: components["schemas"]["CategoryDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        ApiResponseOfCategoryDto: {
            data: components["schemas"]["CategoryDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateCategoryDto: {
            name: string;
            slug: string;
            description?: string;
            /** @default 0 */
            sort_order: number;
        };
        UpdateCategoryDto: {
            name?: string;
            slug?: string;
            description?: string;
            /** @default 0 */
            sort_order: number;
        };
        ProductDto: {
            id: number;
            name: string;
            slug: string;
            description: string | null;
            price: number;
            sale_price: number | null;
            /** @enum {string} */
            status: "in_stock" | "made_to_order" | "out_of_stock";
            new_category: {
                id: number;
                name: string;
                slug: string;
            };
            variants: {
                id: number;
                color: string | null;
                size: string | null;
                child_name: string | null;
                stock: number;
            }[];
            image_urls: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiArrayResponseOfProductDto: {
            data: components["schemas"]["ProductDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        ApiResponseOfProductDto: {
            data: components["schemas"]["ProductDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateProductDto: {
            name: string;
            slug: string;
            description?: string;
            category_id: number;
            /**
             * @default in_stock
             * @enum {string}
             */
            status: "in_stock" | "made_to_order" | "out_of_stock";
            price: number;
            sale_price?: number;
            image_file_ids?: number[];
        };
        UpdateProductDto: {
            name?: string;
            slug?: string;
            description?: string;
            category_id?: number;
            /**
             * @default in_stock
             * @enum {string}
             */
            status: "in_stock" | "made_to_order" | "out_of_stock";
            price?: number;
            sale_price?: number;
            image_file_ids?: number[];
        };
        CreateVariantDto: {
            color?: string;
            size?: string;
            child_name?: string;
            /** @default 0 */
            stock: number;
        };
        ProductVariantDto: {
            id: number;
            color: string | null;
            size: string | null;
            child_name: string | null;
            stock: number;
        };
        ApiResponseOfProductVariantDto: {
            data: components["schemas"]["ProductVariantDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        UpdateVariantDto: {
            color?: string;
            size?: string;
            child_name?: string;
            /** @default 0 */
            stock: number;
        };
        FileDto: {
            id: number;
            original_name: string;
            size: number;
            ext: string;
            mimetype: string;
            s3_url: string;
            /** Format: date-time */
            created_at: string;
        };
        ApiResponseOfFileDto: {
            data: components["schemas"]["FileDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateOrderDto: {
            guest_name: string;
            /** Format: email */
            guest_email: string;
            guest_phone: string;
            address: string;
            nova_poshta_ref?: string;
            /** @enum {string} */
            payment_method: "online" | "cash_on_delivery";
            notes?: string;
            items: {
                variant_id: number;
                quantity: number;
            }[];
        };
        OrderDto: {
            id: number;
            guest_name: string;
            guest_email: string;
            guest_phone: string;
            address: string;
            nova_poshta_ref: string | null;
            /** @enum {string} */
            payment_method: "online" | "cash_on_delivery";
            /** @enum {string} */
            payment_status: "pending" | "paid" | "failed";
            /** @enum {string} */
            status: "new" | "processing" | "shipped" | "delivered" | "cancelled";
            total_price: number;
            notes: string | null;
            items: {
                id: number;
                variant_id: number;
                quantity: number;
                price: number;
                variant: {
                    id: number;
                    color: string | null;
                    size: string | null;
                    child_name: string | null;
                };
            }[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiResponseOfOrderDto: {
            data: components["schemas"]["OrderDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        ApiArrayResponseOfOrderDto: {
            data: components["schemas"]["OrderDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        UpdateOrderStatusDto: {
            /** @enum {string} */
            status: "new" | "processing" | "shipped" | "delivered" | "cancelled";
            /** @enum {string} */
            payment_status?: "pending" | "paid" | "failed";
        };
        ReviewDto: {
            id: number;
            product_id: number;
            author_name: string;
            author_email: string | null;
            rating: number;
            body: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiArrayResponseOfReviewDto: {
            data: components["schemas"]["ReviewDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateReviewDto: {
            product_id: number;
            author_name: string;
            /** Format: email */
            author_email?: string;
            rating: number;
            body: string;
        };
        ApiResponseOfReviewDto: {
            data: components["schemas"]["ReviewDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        UpdateReviewStatusDto: {
            /** @enum {string} */
            status: "pending" | "approved" | "rejected";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfLoginResponseDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfRefreshResponseDto"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfAuthUserDto"];
                };
            };
        };
    };
    AuthController_logout_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutDto"];
            };
        };
        responses: {
            /** @description Logged out successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersAdminController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfUserDto"];
                };
            };
        };
    };
    UsersAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfUserDto"];
                };
            };
        };
    };
    UsersAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfUserDto"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfUserDto"];
                };
            };
        };
    };
    CategoriesController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfCategoryDto"];
                };
            };
        };
    };
    CategoriesController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfCategoryDto"];
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesAdminController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfCategoryDto"];
                };
            };
        };
    };
    CategoriesAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfCategoryDto"];
                };
            };
        };
    };
    CategoriesAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfCategoryDto"];
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfCategoryDto"];
                };
            };
        };
    };
    ProductsController_findAll_v1: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                category_id?: number;
                status?: "in_stock" | "made_to_order" | "out_of_stock";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfProductDto"];
                };
            };
        };
    };
    ProductsController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfProductDto"];
                };
            };
        };
    };
    ProductsAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
        };
    };
    ProductsAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
        };
    };
    ProductsAdminController_createVariant_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVariantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductVariantDto"];
                };
            };
        };
    };
    ProductsAdminController_removeVariant_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                variantId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_updateVariant_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                variantId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVariantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductVariantDto"];
                };
            };
        };
    };
    FilesController_upload_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfFileDto"];
                };
            };
        };
    };
    OrdersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfOrderDto"];
                };
            };
        };
    };
    OrdersController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfOrderDto"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersAdminController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfOrderDto"];
                };
            };
        };
    };
    OrdersAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfOrderDto"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersAdminController_updateStatus_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfOrderDto"];
                };
            };
        };
    };
    ReviewsController_findByProduct_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfReviewDto"];
                };
            };
        };
    };
    ReviewsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfReviewDto"];
                };
            };
        };
    };
    ReviewsAdminController_findAll_v1: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                product_id?: number;
                status?: "pending" | "approved" | "rejected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfReviewDto"];
                };
            };
        };
    };
    ReviewsAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfReviewDto"];
                };
            };
            /** @description Review not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsAdminController_updateStatus_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfReviewDto"];
                };
            };
        };
    };
}
