/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["AuthController_refresh_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["AuthController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate refresh token */
        post: operations["AuthController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users (admin) */
        get: operations["UsersAdminController_findAll_v1"];
        put?: never;
        /** Create user */
        post: operations["UsersAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by id (admin) */
        get: operations["UsersAdminController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete user */
        delete: operations["UsersAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Update user */
        patch: operations["UsersAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories */
        get: operations["CategoriesController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get categories as a nested tree (each node carries `children`) */
        get: operations["CategoriesController_findTree_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category by slug */
        get: operations["CategoriesController_findOne_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories (admin) */
        get: operations["CategoriesAdminController_findAll_v1"];
        put?: never;
        /** Create category */
        post: operations["CategoriesAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category by id (admin) */
        get: operations["CategoriesAdminController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete category */
        delete: operations["CategoriesAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Update category */
        patch: operations["CategoriesAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get attribute definitions (optionally scoped to a category) */
        get: operations["AttributesController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all attributes (admin) */
        get: operations["AttributesAdminController_findAll_v1"];
        put?: never;
        /** Create attribute */
        post: operations["AttributesAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/attributes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get attribute by id (admin) */
        get: operations["AttributesAdminController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete attribute */
        delete: operations["AttributesAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Update attribute */
        patch: operations["AttributesAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/admin/attributes/{id}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an option to a select-like attribute */
        post: operations["AttributesAdminController_createOption_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/attributes/{id}/options/{optionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an attribute option */
        delete: operations["AttributesAdminController_removeOption_v1"];
        options?: never;
        head?: never;
        /** Update an attribute option */
        patch: operations["AttributesAdminController_updateOption_v1"];
        trace?: never;
    };
    "/api/v1/admin/categories/{categoryId}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attributes wired to a category */
        get: operations["CategoryAttributesAdminController_findAll_v1"];
        /** Replace the attribute set of a category */
        put: operations["CategoryAttributesAdminController_set_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse published products */
        get: operations["ProductsController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by slug */
        get: operations["ProductsController_findOne_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all products (admin, incl. drafts) */
        get: operations["ProductsAdminController_findAll_v1"];
        put?: never;
        /** Create product */
        post: operations["ProductsAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by id (admin) */
        get: operations["ProductsAdminController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete product */
        delete: operations["ProductsAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Update product */
        patch: operations["ProductsAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/admin/products/{id}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a variation axis (Colour, Size, …) */
        post: operations["ProductsAdminController_createOption_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{id}/options/{optionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a variation axis */
        delete: operations["ProductsAdminController_removeOption_v1"];
        options?: never;
        head?: never;
        /** Update a variation axis */
        patch: operations["ProductsAdminController_updateOption_v1"];
        trace?: never;
    };
    "/api/v1/admin/products/{id}/options/{optionId}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a choice to a variation axis */
        post: operations["ProductsAdminController_createOptionValue_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{id}/options/{optionId}/values/{valueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a choice on a variation axis */
        delete: operations["ProductsAdminController_removeOptionValue_v1"];
        options?: never;
        head?: never;
        /** Update a choice on a variation axis */
        patch: operations["ProductsAdminController_updateOptionValue_v1"];
        trace?: never;
    };
    "/api/v1/admin/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create product variant */
        post: operations["ProductsAdminController_createVariant_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{id}/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete product variant */
        delete: operations["ProductsAdminController_removeVariant_v1"];
        options?: never;
        head?: never;
        /** Update product variant */
        patch: operations["ProductsAdminController_updateVariant_v1"];
        trace?: never;
    };
    "/api/v1/admin/products/{id}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace every attribute value of a product */
        put: operations["ProductsAdminController_setAttributes_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append uploaded files to the gallery (keeps existing images) */
        post: operations["ProductsAdminController_addImages_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{id}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a single product image */
        delete: operations["ProductsAdminController_removeImage_v1"];
        options?: never;
        head?: never;
        /** Update one image (alt, order, variant binding) */
        patch: operations["ProductsAdminController_updateImage_v1"];
        trace?: never;
    };
    "/api/v1/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file to temporary storage */
        post: operations["FilesController_upload_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create order */
        post: operations["OrdersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order by id */
        get: operations["OrdersController_findOne_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all orders (admin) */
        get: operations["OrdersAdminController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order by id (admin) */
        get: operations["OrdersAdminController_findOne_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update order status */
        patch: operations["OrdersAdminController_updateStatus_v1"];
        trace?: never;
    };
    "/api/v1/reviews/product/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get approved reviews for a product */
        get: operations["ReviewsController_findByProduct_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a review */
        post: operations["ReviewsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all reviews (admin) */
        get: operations["ReviewsAdminController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get review by id (admin) */
        get: operations["ReviewsAdminController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete review */
        delete: operations["ReviewsAdminController_remove_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reviews/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update review status */
        patch: operations["ReviewsAdminController_updateStatus_v1"];
        trace?: never;
    };
    "/api/v1/configurator/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all active configurator options */
        get: operations["ConfiguratorController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurator/options/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get configurator option by id */
        get: operations["ConfiguratorController_findOne_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/configurator/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all configurator options (admin) */
        get: operations["ConfiguratorAdminController_findAll_v1"];
        put?: never;
        /** Create configurator option */
        post: operations["ConfiguratorAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/configurator/options/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get configurator option by id (admin) */
        get: operations["ConfiguratorAdminController_findOne_v1"];
        put?: never;
        post?: never;
        /** Delete configurator option */
        delete: operations["ConfiguratorAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Update configurator option */
        patch: operations["ConfiguratorAdminController_update_v1"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponseDto: {
            user: {
                id: number;
                email: string;
                first_name: string;
                last_name: string;
                /** @enum {string} */
                role: "admin" | "user";
                /** Format: date-time */
                created_at: string;
            };
            access_token: string;
            refresh_token: string;
            access_expires_at: string;
        };
        ApiResponseOfLoginResponseDto: {
            data: components["schemas"]["LoginResponseDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        RefreshDto: {
            refresh_token: string;
        };
        RefreshResponseDto: {
            access_token: string;
            access_expires_at: string;
        };
        ApiResponseOfRefreshResponseDto: {
            data: components["schemas"]["RefreshResponseDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        AuthUserDto: {
            id: number;
            email: string;
            first_name: string;
            last_name: string;
            /** @enum {string} */
            role: "admin" | "user";
            /** Format: date-time */
            created_at: string;
        };
        ApiResponseOfAuthUserDto: {
            data: components["schemas"]["AuthUserDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        LogoutDto: {
            refresh_token: string;
        };
        UserDto: {
            id: number;
            email: string;
            first_name: string;
            last_name: string;
            /** @enum {string} */
            role: "admin" | "user";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiArrayResponseOfUserDto: {
            data: components["schemas"]["UserDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        ApiResponseOfUserDto: {
            data: components["schemas"]["UserDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateUserDto: {
            /** Format: email */
            email: string;
            password: string;
            first_name: string;
            last_name: string;
            /**
             * @default user
             * @enum {string}
             */
            role: "admin" | "user";
        };
        UpdateUserDto: {
            /** Format: email */
            email?: string;
            password?: string;
            first_name?: string;
            last_name?: string;
            /**
             * @default user
             * @enum {string}
             */
            role: "admin" | "user";
        };
        CategoryDto: {
            id: number;
            name: string;
            slug: string;
            description: string | null;
            parent_id: number | null;
            image_url: string | null;
            meta_title: string | null;
            meta_description: string | null;
            sort_order: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiArrayResponseOfCategoryDto: {
            data: components["schemas"]["CategoryDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        ApiResponseOfCategoryDto: {
            data: components["schemas"]["CategoryDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateCategoryDto: {
            name: string;
            slug: string;
            description?: string | null;
            parent_id?: number | null;
            /** Format: uri */
            image_url?: string | null;
            meta_title?: string | null;
            meta_description?: string | null;
            /** @default 0 */
            sort_order: number;
        };
        UpdateCategoryDto: {
            name?: string;
            slug?: string;
            description?: string | null;
            parent_id?: number | null;
            /** Format: uri */
            image_url?: string | null;
            meta_title?: string | null;
            meta_description?: string | null;
            /** @default 0 */
            sort_order: number;
        };
        AttributeDto: {
            id: number;
            code: string;
            name: string;
            /** @enum {string} */
            type: "text" | "richtext" | "number" | "boolean" | "select" | "multiselect" | "color" | "image" | "url" | "date";
            unit: string | null;
            group_name: string | null;
            is_filterable: boolean;
            is_visible: boolean;
            sort_order: number;
            options: {
                id: number;
                label: string;
                value: string;
                color_hex: string | null;
                image_url: string | null;
                sort_order: number;
            }[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiArrayResponseOfAttributeDto: {
            data: components["schemas"]["AttributeDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        ApiResponseOfAttributeDto: {
            data: components["schemas"]["AttributeDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateAttributeDto: {
            code: string;
            name: string;
            /** @enum {string} */
            type: "text" | "richtext" | "number" | "boolean" | "select" | "multiselect" | "color" | "image" | "url" | "date";
            unit?: string | null;
            group_name?: string | null;
            is_filterable?: boolean;
            is_visible?: boolean;
            sort_order?: number;
            options?: {
                label: string;
                value: string;
                color_hex?: string | null;
                /** Format: uri */
                image_url?: string | null;
                sort_order?: number;
            }[];
        };
        UpdateAttributeDto: {
            code?: string;
            name?: string;
            unit?: string | null;
            group_name?: string | null;
            is_filterable?: boolean;
            is_visible?: boolean;
            sort_order?: number;
        };
        CreateAttributeOptionDto: {
            label: string;
            value: string;
            color_hex?: string | null;
            /** Format: uri */
            image_url?: string | null;
            sort_order?: number;
        };
        AttributeOptionDto: {
            id: number;
            label: string;
            value: string;
            color_hex: string | null;
            image_url: string | null;
            sort_order: number;
        };
        ApiResponseOfAttributeOptionDto: {
            data: components["schemas"]["AttributeOptionDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        UpdateAttributeOptionDto: {
            label?: string;
            value?: string;
            color_hex?: string | null;
            /** Format: uri */
            image_url?: string | null;
            sort_order?: number;
        };
        SetCategoryAttributesDto: {
            attributes: {
                attribute_id: number;
                is_required?: boolean;
                sort_order?: number;
            }[];
        };
        ProductDto: {
            id: number;
            name: string;
            slug: string;
            sku: string | null;
            brand: string | null;
            short_description: string | null;
            description: string | null;
            /** @enum {string} */
            status: "in_stock" | "made_to_order" | "out_of_stock";
            is_featured: boolean;
            currency: string;
            price: number;
            compare_at_price: number | null;
            sale_price: number | null;
            sale_active: boolean;
            /** Format: date-time */
            sale_starts_at: string | null;
            /** Format: date-time */
            sale_ends_at: string | null;
            effective_price: number;
            price_range: {
                min: number;
                max: number;
            };
            stock: number;
            category: {
                id: number;
                name: string;
                slug: string;
            };
            options: {
                id: number;
                name: string;
                sort_order: number;
                values: {
                    id: number;
                    label: string;
                    value: string;
                    color_hex: string | null;
                    image_url: string | null;
                    sort_order: number;
                }[];
            }[];
            variants: {
                id: number;
                sku: string | null;
                label: string;
                stock: number;
                is_default: boolean;
                sort_order: number;
                price: number;
                compare_at_price: number | null;
                effective_price: number;
                sale_active: boolean;
                option_values: {
                    option_id: number;
                    option_name: string;
                    value_id: number;
                    label: string;
                    value: string;
                    color_hex: string | null;
                    image_url: string | null;
                }[];
                image_ids: number[];
                attributes: {
                    id: number;
                    code: string;
                    name: string;
                    /** @enum {string} */
                    type: "text" | "richtext" | "number" | "boolean" | "select" | "multiselect" | "color" | "image" | "url" | "date";
                    unit: string | null;
                    group_name: string | null;
                    is_filterable: boolean;
                    sort_order: number;
                    value: (string | number | boolean | {
                        id: number;
                        label: string;
                        value: string;
                        color_hex: string | null;
                        image_url: string | null;
                    } | {
                        id: number;
                        label: string;
                        value: string;
                        color_hex: string | null;
                        image_url: string | null;
                    }[]) | null;
                }[];
            }[];
            attributes: {
                id: number;
                code: string;
                name: string;
                /** @enum {string} */
                type: "text" | "richtext" | "number" | "boolean" | "select" | "multiselect" | "color" | "image" | "url" | "date";
                unit: string | null;
                group_name: string | null;
                is_filterable: boolean;
                sort_order: number;
                value: (string | number | boolean | {
                    id: number;
                    label: string;
                    value: string;
                    color_hex: string | null;
                    image_url: string | null;
                } | {
                    id: number;
                    label: string;
                    value: string;
                    color_hex: string | null;
                    image_url: string | null;
                }[]) | null;
            }[];
            specs: {
                [key: string]: (string | number | boolean) | null;
            };
            images: {
                id: number;
                url: string;
                alt: string | null;
                variant_id: number | null;
                sort_order: number;
            }[];
            meta_title: string | null;
            meta_description: string | null;
            /** Format: date-time */
            published_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PaginationMetaClass: {
            total: number;
            page: number;
            limit: number;
            pages: number;
        };
        PaginatedPayloadClass: {
            items: components["schemas"]["ProductDto"][];
            meta: components["schemas"]["PaginationMetaClass"];
        };
        ApiPaginatedResponseOfProductDto: {
            data: components["schemas"]["PaginatedPayloadClass"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        ApiResponseOfProductDto: {
            data: components["schemas"]["ProductDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateProductDto: {
            name: string;
            slug: string;
            sku?: string | null;
            brand?: string | null;
            short_description?: string | null;
            description?: string | null;
            category_id: number;
            /**
             * @default in_stock
             * @enum {string}
             */
            status: "in_stock" | "made_to_order" | "out_of_stock";
            price: number;
            compare_at_price?: number | null;
            sale_price?: number | null;
            /** Format: date-time */
            sale_starts_at?: string | null;
            /** Format: date-time */
            sale_ends_at?: string | null;
            currency?: string;
            stock?: number;
            specs?: {
                [key: string]: (string | number | boolean) | null;
            } | null;
            meta_title?: string | null;
            meta_description?: string | null;
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
            image_file_ids?: number[];
        };
        UpdateProductDto: {
            name?: string;
            slug?: string;
            sku?: string | null;
            brand?: string | null;
            short_description?: string | null;
            description?: string | null;
            category_id?: number;
            /** @enum {string} */
            status?: "in_stock" | "made_to_order" | "out_of_stock";
            price?: number;
            compare_at_price?: number | null;
            sale_price?: number | null;
            /** Format: date-time */
            sale_starts_at?: string | null;
            /** Format: date-time */
            sale_ends_at?: string | null;
            currency?: string;
            stock?: number;
            specs?: {
                [key: string]: (string | number | boolean) | null;
            } | null;
            meta_title?: string | null;
            meta_description?: string | null;
            is_featured?: boolean;
            /** Format: date-time */
            published_at?: string | null;
            image_file_ids?: number[];
        };
        CreateOptionDto: {
            name: string;
            sort_order?: number;
            values?: {
                label: string;
                value: string;
                color_hex?: string | null;
                /** Format: uri */
                image_url?: string | null;
                sort_order?: number;
            }[];
        };
        ProductOptionDto: {
            id: number;
            name: string;
            sort_order: number;
            values: {
                id: number;
                label: string;
                value: string;
                color_hex: string | null;
                image_url: string | null;
                sort_order: number;
            }[];
        };
        ApiResponseOfProductOptionDto: {
            data: components["schemas"]["ProductOptionDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        UpdateOptionDto: {
            name?: string;
            sort_order?: number;
        };
        CreateOptionValueDto: {
            label: string;
            value: string;
            color_hex?: string | null;
            /** Format: uri */
            image_url?: string | null;
            sort_order?: number;
        };
        ProductOptionValueDto: {
            id: number;
            label: string;
            value: string;
            color_hex: string | null;
            image_url: string | null;
            sort_order: number;
        };
        ApiResponseOfProductOptionValueDto: {
            data: components["schemas"]["ProductOptionValueDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        UpdateOptionValueDto: {
            label?: string;
            value?: string;
            color_hex?: string | null;
            /** Format: uri */
            image_url?: string | null;
            sort_order?: number;
        };
        CreateVariantDto: {
            sku?: string | null;
            price?: number | null;
            compare_at_price?: number | null;
            /** @default 0 */
            stock: number;
            is_default?: boolean;
            sort_order?: number;
            /** @default [] */
            option_value_ids: number[];
        };
        ProductVariantDto: {
            id: number;
            sku: string | null;
            label: string;
            stock: number;
            is_default: boolean;
            sort_order: number;
            price: number;
            compare_at_price: number | null;
            effective_price: number;
            sale_active: boolean;
            option_values: {
                option_id: number;
                option_name: string;
                value_id: number;
                label: string;
                value: string;
                color_hex: string | null;
                image_url: string | null;
            }[];
            image_ids: number[];
            attributes: {
                id: number;
                code: string;
                name: string;
                /** @enum {string} */
                type: "text" | "richtext" | "number" | "boolean" | "select" | "multiselect" | "color" | "image" | "url" | "date";
                unit: string | null;
                group_name: string | null;
                is_filterable: boolean;
                sort_order: number;
                value: (string | number | boolean | {
                    id: number;
                    label: string;
                    value: string;
                    color_hex: string | null;
                    image_url: string | null;
                } | {
                    id: number;
                    label: string;
                    value: string;
                    color_hex: string | null;
                    image_url: string | null;
                }[]) | null;
            }[];
        };
        ApiResponseOfProductVariantDto: {
            data: components["schemas"]["ProductVariantDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        UpdateVariantDto: {
            sku?: string | null;
            price?: number | null;
            compare_at_price?: number | null;
            stock?: number;
            is_default?: boolean;
            sort_order?: number;
            option_value_ids?: number[];
        };
        SetProductAttributesDto: {
            attributes: {
                attribute_id: number;
                variant_id?: number | null;
                value: (string | number | boolean | number[]) | null;
            }[];
        };
        AddProductImagesDto: {
            file_ids: number[];
            variant_id?: number | null;
        };
        UpdateProductImageDto: {
            alt?: string | null;
            sort_order?: number;
            variant_id?: number | null;
        };
        FileDto: {
            id: number;
            original_name: string;
            size: number;
            ext: string;
            mimetype: string;
            s3_url: string;
            /** Format: date-time */
            created_at: string;
        };
        ApiResponseOfFileDto: {
            data: components["schemas"]["FileDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateOrderDto: {
            guest_name: string;
            /** Format: email */
            guest_email: string;
            guest_phone: string;
            address: string;
            nova_poshta_ref?: string;
            /** @enum {string} */
            payment_method: "online" | "cash_on_delivery";
            notes?: string;
            items: {
                variant_id?: number;
                product_id?: number;
                quantity: number;
            }[];
        };
        OrderDto: {
            id: number;
            guest_name: string;
            guest_email: string;
            guest_phone: string;
            address: string;
            nova_poshta_ref: string | null;
            /** @enum {string} */
            payment_method: "online" | "cash_on_delivery";
            /** @enum {string} */
            payment_status: "pending" | "paid" | "failed";
            /** @enum {string} */
            status: "new" | "processing" | "shipped" | "delivered" | "cancelled";
            total_price: number;
            notes: string | null;
            items: {
                id: number;
                variant_id: number | null;
                product_id: number | null;
                quantity: number;
                price: number;
                product_name: string | null;
                variant_label: string | null;
                sku: string | null;
                configuration: {
                    [key: string]: unknown;
                } | null;
                variant: {
                    id: number;
                    sku: string | null;
                    stock: number;
                } | null;
                product: {
                    id: number;
                    name: string;
                    slug: string;
                } | null;
            }[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiResponseOfOrderDto: {
            data: components["schemas"]["OrderDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        ApiArrayResponseOfOrderDto: {
            data: components["schemas"]["OrderDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        UpdateOrderStatusDto: {
            /** @enum {string} */
            status: "new" | "processing" | "shipped" | "delivered" | "cancelled";
            /** @enum {string} */
            payment_status?: "pending" | "paid" | "failed";
        };
        ReviewDto: {
            id: number;
            product_id: number;
            author_name: string;
            author_email: string | null;
            rating: number;
            body: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiArrayResponseOfReviewDto: {
            data: components["schemas"]["ReviewDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateReviewDto: {
            product_id: number;
            author_name: string;
            /** Format: email */
            author_email?: string;
            rating: number;
            body: string;
        };
        ApiResponseOfReviewDto: {
            data: components["schemas"]["ReviewDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        UpdateReviewStatusDto: {
            /** @enum {string} */
            status: "pending" | "approved" | "rejected";
        };
        ConfiguratorOptionDto: {
            id: number;
            product_id: number | null;
            /** @enum {string} */
            type: "size" | "fabric" | "color" | "addon";
            label: string;
            value: string;
            price_modifier: number;
            image_url: string | null;
            sort_order: number;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiArrayResponseOfConfiguratorOptionDto: {
            data: components["schemas"]["ConfiguratorOptionDto"][];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        ApiResponseOfConfiguratorOptionDto: {
            data: components["schemas"]["ConfiguratorOptionDto"];
            /** @example 2024-01-01T00:00:00.000Z */
            timestamp: string;
        };
        CreateConfiguratorOptionDto: {
            product_id?: number | null;
            /** @enum {string} */
            type: "size" | "fabric" | "color" | "addon";
            label: string;
            value: string;
            /** @default 0 */
            price_modifier: number;
            /** Format: uri */
            image_url?: string | null;
            /** @default 0 */
            sort_order: number;
            /** @default true */
            is_active: boolean;
        };
        UpdateConfiguratorOptionDto: {
            product_id?: number | null;
            /** @enum {string} */
            type?: "size" | "fabric" | "color" | "addon";
            label?: string;
            value?: string;
            price_modifier?: number;
            /** Format: uri */
            image_url?: string | null;
            sort_order?: number;
            is_active?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfLoginResponseDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfRefreshResponseDto"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfAuthUserDto"];
                };
            };
        };
    };
    AuthController_logout_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutDto"];
            };
        };
        responses: {
            /** @description Logged out successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersAdminController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfUserDto"];
                };
            };
        };
    };
    UsersAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfUserDto"];
                };
            };
        };
    };
    UsersAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfUserDto"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfUserDto"];
                };
            };
        };
    };
    CategoriesController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfCategoryDto"];
                };
            };
        };
    };
    CategoriesController_findTree_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfCategoryDto"];
                };
            };
        };
    };
    CategoriesController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfCategoryDto"];
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesAdminController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfCategoryDto"];
                };
            };
        };
    };
    CategoriesAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfCategoryDto"];
                };
            };
        };
    };
    CategoriesAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfCategoryDto"];
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfCategoryDto"];
                };
            };
        };
    };
    AttributesController_findAll_v1: {
        parameters: {
            query?: {
                category_id?: number;
                is_filterable?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfAttributeDto"];
                };
            };
        };
    };
    AttributesAdminController_findAll_v1: {
        parameters: {
            query?: {
                category_id?: number;
                is_filterable?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfAttributeDto"];
                };
            };
        };
    };
    AttributesAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttributeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfAttributeDto"];
                };
            };
        };
    };
    AttributesAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfAttributeDto"];
                };
            };
            /** @description Attribute not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttributesAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttributesAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttributeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfAttributeDto"];
                };
            };
        };
    };
    AttributesAdminController_createOption_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttributeOptionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfAttributeOptionDto"];
                };
            };
        };
    };
    AttributesAdminController_removeOption_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                optionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttributesAdminController_updateOption_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                optionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttributeOptionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfAttributeOptionDto"];
                };
            };
        };
    };
    CategoryAttributesAdminController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfAttributeDto"];
                };
            };
        };
    };
    CategoryAttributesAdminController_set_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCategoryAttributesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfAttributeDto"];
                };
            };
        };
    };
    ProductsController_findAll_v1: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                category_id?: number;
                include_descendants?: boolean | ("0" | "1" | "true" | "false");
                status?: "in_stock" | "made_to_order" | "out_of_stock";
                search?: string;
                min_price?: number;
                max_price?: number;
                is_featured?: boolean | ("0" | "1" | "true" | "false");
                in_stock?: boolean | ("0" | "1" | "true" | "false");
                sort?: "newest" | "oldest" | "price_asc" | "price_desc" | "name_asc" | "name_desc";
                /** @description Facets keyed by attribute code: attributes[color]=red,blue or attributes[width_cm]=80..120 */
                attributes?: {
                    [key: string]: string;
                };
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiPaginatedResponseOfProductDto"];
                };
            };
        };
    };
    ProductsController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_findAll_v1: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                category_id?: number;
                include_descendants?: boolean | ("0" | "1" | "true" | "false");
                status?: "in_stock" | "made_to_order" | "out_of_stock";
                search?: string;
                min_price?: number;
                max_price?: number;
                is_featured?: boolean | ("0" | "1" | "true" | "false");
                in_stock?: boolean | ("0" | "1" | "true" | "false");
                sort?: "newest" | "oldest" | "price_asc" | "price_desc" | "name_asc" | "name_desc";
                attributes?: {
                    [key: string]: string;
                };
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiPaginatedResponseOfProductDto"];
                };
            };
        };
    };
    ProductsAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
        };
    };
    ProductsAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
        };
    };
    ProductsAdminController_createOption_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOptionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductOptionDto"];
                };
            };
        };
    };
    ProductsAdminController_removeOption_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                optionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_updateOption_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                optionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOptionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductOptionDto"];
                };
            };
        };
    };
    ProductsAdminController_createOptionValue_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                optionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOptionValueDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductOptionValueDto"];
                };
            };
        };
    };
    ProductsAdminController_removeOptionValue_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                optionId: number;
                valueId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_updateOptionValue_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                optionId: number;
                valueId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOptionValueDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductOptionValueDto"];
                };
            };
        };
    };
    ProductsAdminController_createVariant_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVariantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductVariantDto"];
                };
            };
        };
    };
    ProductsAdminController_removeVariant_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                variantId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_updateVariant_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                variantId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVariantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductVariantDto"];
                };
            };
        };
    };
    ProductsAdminController_setAttributes_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetProductAttributesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
        };
    };
    ProductsAdminController_addImages_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProductImagesDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
        };
    };
    ProductsAdminController_removeImage_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                imageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_updateImage_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                imageId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductImageDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfProductDto"];
                };
            };
        };
    };
    FilesController_upload_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfFileDto"];
                };
            };
        };
    };
    OrdersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfOrderDto"];
                };
            };
        };
    };
    OrdersController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfOrderDto"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersAdminController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfOrderDto"];
                };
            };
        };
    };
    OrdersAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfOrderDto"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersAdminController_updateStatus_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfOrderDto"];
                };
            };
        };
    };
    ReviewsController_findByProduct_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfReviewDto"];
                };
            };
        };
    };
    ReviewsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfReviewDto"];
                };
            };
        };
    };
    ReviewsAdminController_findAll_v1: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                product_id?: number;
                status?: "pending" | "approved" | "rejected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfReviewDto"];
                };
            };
        };
    };
    ReviewsAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfReviewDto"];
                };
            };
            /** @description Review not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsAdminController_updateStatus_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfReviewDto"];
                };
            };
        };
    };
    ConfiguratorController_findAll_v1: {
        parameters: {
            query?: {
                type?: "size" | "fabric" | "color" | "addon";
                product_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfConfiguratorOptionDto"];
                };
            };
        };
    };
    ConfiguratorController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfConfiguratorOptionDto"];
                };
            };
            /** @description Option not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConfiguratorAdminController_findAll_v1: {
        parameters: {
            query?: {
                type?: "size" | "fabric" | "color" | "addon";
                product_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiArrayResponseOfConfiguratorOptionDto"];
                };
            };
        };
    };
    ConfiguratorAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConfiguratorOptionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfConfiguratorOptionDto"];
                };
            };
        };
    };
    ConfiguratorAdminController_findOne_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfConfiguratorOptionDto"];
                };
            };
            /** @description Option not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConfiguratorAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Option deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConfiguratorAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConfiguratorOptionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseOfConfiguratorOptionDto"];
                };
            };
        };
    };
}
